# default:
#   plugins:
#     - image
#     - link

# alternate:
#   <<: *default
#   selector: textarea.table-editor
#   toolbar: styleselect | bold italic | undo redo | table
#   plugins:
#     - table
toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link